# Generated by Django 5.0.7 on 2024-09-21 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.product'),
        ),
    ]
