# Generated by Django 5.0.7 on 2024-11-06 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_rename_invoice_order_invoice_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(choices=[('DZ', 'جزائري'), ('EG', 'مصري'), ('TN', 'تونسي'), ('LY', 'ليبي'), ('MA', 'مغربي'), ('SA', 'سعودي'), ('AE', 'إماراتي')], default='DZ', max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
    ]
