# Generated by Django 5.0.7 on 2024-11-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_customer_nationality_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=2),
        ),
    ]
