# Generated by Django 5.0.7 on 2024-11-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_customer_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
